import Footter from "@/components/ui/footter";
import HeaderPage from "@/components/ui/header";
import AuthProvider from "@/provider/authProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" >
      <body className={inter.className}>
        <AuthProvider>
          <HeaderPage />
          <div className="flex-1">{children}</div>
          <Footter />
        </AuthProvider>
        
      </body>
    </html>
  );
}
