import Footter from "@/components/ui/footter";
import Header from "@/components/ui/header";
import { cn } from "@/lib/utils";
import AuthProvider from "@/provider/authProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" >
      <body className={cn(inter.className, "")}>
        <AuthProvider>
          <Header/>
          {children}      
        </AuthProvider>
         <Footter />
      </body>
    </html>
  );
}
